[WEB] [API] Application back
iangg29/tc2007b pull request #43
Opened 2022-09-29 06:01 UTC by karen-baltazar

- [ ] Create Application_Documents queries.
- [ ] Create Application_Documents mutations.
- [ ] Updated Application queries and mutations.
- [ ] Back-end and Front-end connection for Application Documentation Review.

2022-09-29 06:27 UTC, iangg29 requested changes

2022-09-29 06:27 UTC, iangg29 commented on api/source/graphql/mutations/ApplicationDocumentsMutations.ts
> +    },
Unnecessary mutation, `pivot` table should only be used to link models. This `link` part should happen automatically on `Document` or `Application` creation.  Also, within `Document` and `Application` queries opposite objects must be fetched using `pivot` table.

2022-09-29 06:27 UTC, iangg29 commented on api/source/graphql/mutations/ApplicationMutations.ts
> +
Remove debugging `console.log`.

2022-09-29 06:27 UTC, iangg29 commented on api/source/graphql/mutations/AuthMutations.ts
> +};
Authentication is no longer handled with graphql. Remove file.

2022-09-29 06:27 UTC, iangg29 commented on api/source/graphql/mutations/UserMutations.ts
> +};
Authentication is no longer handled with graphql. Remove file.

2022-09-29 06:27 UTC, iangg29 commented on api/source/graphql/queries/ApplicationQueries.ts
> +  },
Pull relationship objects.

2022-09-29 06:27 UTC, iangg29 commented on api/source/types/ApplicationLabelType.ts
> +  },
Remove unused code. This Type was already assigned to @alfredohuerta

2022-09-29 06:27 UTC, iangg29 commented on web/package.json
>      "react-router-dom": "^6.3.0",
Modals are being implemented with [flowbite](https://flowbite-react.com/modal).

2022-09-29 06:27 UTC, iangg29 commented on web/src/components/RequestCard/RequestCard.tsx
>              </div>
Update route names. (English & lowercase).

2022-09-29 06:27 UTC, iangg29 commented on web/src/components/includes/navBar/ArrowDrop.tsx
> +              </Link>
Modify route names (English & lowercase).

2022-09-29 06:27 UTC, iangg29 commented on web/src/pages/Req_Detail.tsx
> +  );
Add document list object within application model and handle fetching inside the query.

2022-09-29 06:27 UTC, iangg29 commented on web/src/pages/suppRequests/ApplicationAccepted.tsx
> +              image={back}
Split conditional rendering condition.

2022-09-29 06:27 UTC, iangg29 commented on web/src/pages/suppRequests/ApplicationFinalized.tsx
> +
If query arguments can be sent null modify schema and handle null values inside query resolver.

2022-09-29 06:27 UTC, iangg29 commented on web/src/pages/suppRequests/ApplicationFinalized.tsx
> +              proyectTile={element.title}
Simplify conditional rendering condition.

2022-09-29 06:27 UTC, iangg29 commented on web/src/pages/suppRequests/ApproveApplication.tsx
> +  const exampleLabels = [{ label: "Cultura" }, { label: "Baile" }];
If query arguments can be sent null modify schema and handle null values inside query resolver.

2022-09-29 06:27 UTC, iangg29 commented on web/src/pages/suppRequests/ApproveApplication.tsx
> +              image={back}
Simplify conditional rendering condition.

2022-09-29 06:27 UTC, iangg29 commented on web/src/pages/suppRequests/ApproveDoc.tsx
> +
This change will **break produciton**. Fixed IDs should **never** be implemented.

2022-09-30 21:51 UTC, alfredohuerta commented on api/source/graphql/mutations/ApplicationMutations.ts
> +    },
Before deleting the application, check if the application exist

2022-09-30 22:02 UTC, alfredohuerta commented on api/source/graphql/queries/UserQueries.ts
> +    },
Delete un-used query

2022-09-30 22:04 UTC, alfredohuerta commented on api/source/types/ApplicationLabelType.ts
> +});
Delete unused type

2022-09-30 22:09 UTC, alfredohuerta commented on api/source/types/ApplicationType.ts
> +    },
Add labeltype as a GraphQLList

2022-09-30 22:18 UTC, alfredohuerta commented on web/src/pages/Chat/Chat.tsx
> +export default Chat;
Delete unused view

2022-09-30 22:22 UTC, alfredohuerta commented on web/src/routes/index.ts
> +  },
delete unused path

2022-09-30 22:22 UTC, alfredohuerta requested changes
Change comments

2022-09-30 22:48 UTC, alfredohuerta requested changes

2022-09-30 22:48 UTC, alfredohuerta commented on api/source/graphql/queries/UserQueries.ts
> +    },
delete unused query

2022-09-30 22:54 UTC, alfredohuerta approved these changes

2022-09-30 23:04 UTC, merged