Citations
iangg29/tc2007b pull request #46
Opened 2022-09-30 01:39 UTC by ArisbethAg

- [x] Added CitationDocuments migration and type.
- [x] Added inserts to Citation_documents table.
- [x] Added queries related to Citation_documents.
- [x] Connected front and back for createCitation.

2022-09-30 03:46 UTC, iangg29 requested changes
LGTM 🤓
Just fix minor comments.

2022-09-30 03:46 UTC, iangg29 commented on api/source/controllers/citation.controller.ts
> +
Empty file?

2022-09-30 03:46 UTC, iangg29 commented on api/source/database/migrations/20220909221517_citations.ts
> +      //   .deferrable("deferred");
Remove commented code.

2022-09-30 03:46 UTC, iangg29 commented on api/source/database/migrations/20220928050507_citation_documents.ts
> +  }
Implement `onUpdate` and `onDelete` methods. See other migration files as reference.

2022-09-30 21:59 UTC, Naiztu approved these changes
I like it

2022-10-01 23:51 UTC, Naiztu approved these changes
It looks good!

2022-10-01 23:53 UTC, merged