45 knex seed database
iangg29/tc2007b pull request #56
Opened 2022-10-05 04:57 UTC by Naiztu

##### CHANGE LOG
- [x] Added seeds initial for the migrations

2022-10-05 06:07 UTC, iangg29 requested changes

2022-10-05 06:07 UTC, iangg29 commented on api/.env.example
>  JWT_COOKIE_EXPIRES_IN=60
Do not change `.env.example`.

2022-10-05 06:07 UTC, iangg29 commented on api/source/graphql/mutations/UserMutation.ts
> +};
User creation is no longer handled with GraphQL. (REST implementation is already created)

Delete file.

2022-10-05 06:07 UTC, iangg29 commented on api/source/types/UserType.ts
>        type: GraphQLNonNull(GraphQLString),
Do not need to get Role ID. Role filed has already been implemented above. Remove this unnecessary field.

2022-10-05 06:08 UTC, iangg29 commented
@Naiztu , tests for this PR are not passing. Please fix existing errors.

2022-10-06 05:28 UTC, iangg29 approved these changes
LGTM

2022-10-06 20:56 UTC, A13xMtzL approved these changes
Berrhy gud

2022-10-06 21:44 UTC, merged