Front sign up
iangg29/tc2007b pull request #79
Opened 2022-10-18 16:24 UTC by JordanaBM

##### CHANGELOG

- [x] Added Basic Style to SignUp
- [x] Added Link to SignUp

2022-10-18 21:44 UTC, A13xMtzL requested changes

2022-10-18 21:44 UTC, A13xMtzL commented on web/src/pages/auth/SignUp.tsx
>        <div className="text-center space-y-10">
Remove commented img.

2022-10-20 02:50 UTC, iangg29 approved these changes
LGTM

2022-10-20 03:02 UTC, A13xMtzL approved these changes
To' bien

2022-10-20 03:05 UTC, merged